FROM --platform=linux/amd64 golang:1.20.4-bullseye@sha256:a26419b6614b675026d1ec6737ae7a9e9ac62ffd799af85dd1269cf88ddd51d3
LABEL maintainer="Fleet Developers"

RUN apt-get update && apt-get install -y \
	gcc \
	libgtk-3-dev \
	libayatana-appindicator3-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/src/fleet
RUN mkdir -p /output

WORKDIR /usr/src/fleet

COPY orbit ./orbit
COPY server ./server
COPY ee ./ee
COPY pkg ./pkg
COPY go.mod go.sum ./

CMD /bin/bash
